#!/bin/bash
# Usage: driver.sh [--tasks a,b,c] [--models m1,m2] [--conditions bare,shipped] [--trials N] [--only-verify]
#
# Runs the full task × model × condition × trial matrix, one cell at a time,
# and verifies each cell right after it runs. Resumable: a cell whose
# .verdict.json exists is skipped, a cell whose .patch exists but has no
# verdict is only verified. Safe to re-run after a rate-limit stop or a reboot.
#
# All per-cell output goes to files (results/<task>/<cell>.*); this script
# prints one line per cell. Do not edit this file while it runs.
set -uo pipefail
source "$(dirname "$0")/lib.sh"

TASKS=""; MODELS="claude-sonnet-5,claude-opus-5,claude-haiku-4-5-20251001"; CONDS="bare,shipped"; TRIALS=3; ONLY_VERIFY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --tasks) TASKS="$2"; shift 2;;
    --models) MODELS="$2"; shift 2;;
    --conditions) CONDS="$2"; shift 2;;
    --trials) TRIALS="$2"; shift 2;;
    --only-verify) ONLY_VERIFY=1; shift;;
    *) echo "unknown arg: $1"; exit 2;;
  esac
done
if [ -z "$TASKS" ]; then
  TASKS="$(cd "$BENCH_ROOT/tasks" && ls -d */ | tr -d / | grep -v '^_' | tr '\n' ',' | sed 's/,$//')"
fi
IFS=, read -ra TASK_LIST <<< "$TASKS"
IFS=, read -ra MODEL_LIST <<< "$MODELS"
IFS=, read -ra COND_LIST <<< "$CONDS"

LOAD="$(uptime | sed 's/.*load averages*: *//')"
echo "== driver start $(date '+%F %T') | load: $LOAD | tasks=${#TASK_LIST[@]} models=${#MODEL_LIST[@]} conds=${#COND_LIST[@]} trials=$TRIALS"
DONE=0; RAN=0; SKIP=0; ERR=0
# Trials outermost so partial progress covers the whole matrix at N=1 first.
for TRIAL in $(seq 1 "$TRIALS"); do
 for TASK in "${TASK_LIST[@]}"; do
  for MODEL in "${MODEL_LIST[@]}"; do
   for COND in "${COND_LIST[@]}"; do
    CELL="$(cell_id "$TASK" "$MODEL" "$COND" "$TRIAL")"; OUT="$RESULTS/$CELL"
    mkdir -p "$RESULTS/$TASK"
    if [ -f "$OUT.verdict.json" ]; then SKIP=$((SKIP+1)); continue; fi
    if [ ! -f "$OUT.patch" ]; then
      if [ "$ONLY_VERIFY" = 1 ]; then continue; fi
      bash "$BENCH_ROOT/harness/run.sh" "$TASK" "$MODEL" "$COND" "$TRIAL" > "$RESULTS/$TASK/$(basename "$OUT").run.log" 2>&1
      RC=$?
      if [ $RC -ne 0 ]; then echo "!! run failed rc=$RC $CELL"; ERR=$((ERR+1)); continue; fi
      # Auth / API failures produce an is_error result with an empty patch:
      # stop the driver rather than burn the matrix on a dead session.
      if python3 - "$OUT.result.json" <<'PY'
import json,sys
r=json.load(open(sys.argv[1]))
sys.exit(0 if r.get('is_error') and r.get('terminal_reason') == 'api_error' else 1)
PY
      then MSG="$(python3 -c "import json,sys;print(str(json.load(open(sys.argv[1])).get('result',''))[:120])" "$OUT.result.json")"; echo "!! api error in $CELL ($MSG) — stopping; the cell re-runs on the next driver start"; rm -f "$OUT.patch"; exit 3; fi
      RAN=$((RAN+1))
    fi
    bash "$BENCH_ROOT/harness/verify.sh" "$TASK" "$MODEL" "$COND" "$TRIAL" > "$RESULTS/$TASK/$(basename "$OUT").verify.log" 2>&1
    STATUS="$(python3 -c "import json,sys;print(json.load(open(sys.argv[1])).get('status','?'))" "$OUT.verdict.json" 2>/dev/null || echo '?')"
    DONE=$((DONE+1))
    echo "$(date '+%T') $CELL → $STATUS"
   done
  done
 done
done
echo "== driver end $(date '+%F %T') | ran=$RAN verified=$DONE skipped=$SKIP errors=$ERR"
